package net.itskittyyoutube.kitty.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.itskittyyoutube.kitty.block.ModBlocks;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        RegistryWrapper.Impl<Enchantment> impl = this.registries.getOrThrow(RegistryKeys.ENCHANTMENT);

        addDrop(ModBlocks.PLANKS_TEMPLATE);
        addDrop(ModBlocks.WHITE_PLANKS);
        addDrop(ModBlocks.WHITE_STAIRS);
        addDrop(ModBlocks.WHITE_SLAB, slabDrops(ModBlocks.WHITE_SLAB));
        addDrop(ModBlocks.WHITE_FENCE);
        addDrop(ModBlocks.WHITE_FENCE_GATE);
        addDrop(ModBlocks.WHITE_DOOR, doorDrops(ModBlocks.WHITE_DOOR));
        addDrop(ModBlocks.WHITE_TRAPDOOR);
        addDrop(ModBlocks.WHITE_PRESSURE_PLATE);
        addDrop(ModBlocks.WHITE_BUTTON);
        addDrop(ModBlocks.LIGHT_GRAY_PLANKS);
        addDrop(ModBlocks.LIGHT_GRAY_STAIRS);
        addDrop(ModBlocks.LIGHT_GRAY_SLAB, slabDrops(ModBlocks.LIGHT_GRAY_SLAB));
        addDrop(ModBlocks.LIGHT_GRAY_FENCE);
        addDrop(ModBlocks.LIGHT_GRAY_FENCE_GATE);
        addDrop(ModBlocks.LIGHT_GRAY_DOOR, doorDrops(ModBlocks.LIGHT_GRAY_DOOR));
        addDrop(ModBlocks.LIGHT_GRAY_TRAPDOOR);
        addDrop(ModBlocks.LIGHT_GRAY_PRESSURE_PLATE);
        addDrop(ModBlocks.LIGHT_GRAY_BUTTON);
        addDrop(ModBlocks.GRAY_PLANKS);
        addDrop(ModBlocks.GRAY_STAIRS);
        addDrop(ModBlocks.GRAY_SLAB, slabDrops(ModBlocks.GRAY_SLAB));
        addDrop(ModBlocks.GRAY_FENCE);
        addDrop(ModBlocks.GRAY_FENCE_GATE);
        addDrop(ModBlocks.GRAY_DOOR, doorDrops(ModBlocks.GRAY_DOOR));
        addDrop(ModBlocks.GRAY_TRAPDOOR);
        addDrop(ModBlocks.GRAY_PRESSURE_PLATE);
        addDrop(ModBlocks.GRAY_BUTTON);
        addDrop(ModBlocks.BLACK_PLANKS);
        addDrop(ModBlocks.BLACK_STAIRS);
        addDrop(ModBlocks.BLACK_SLAB, slabDrops(ModBlocks.BLACK_SLAB));
        addDrop(ModBlocks.BLACK_FENCE);
        addDrop(ModBlocks.BLACK_FENCE_GATE);
        addDrop(ModBlocks.BLACK_DOOR, doorDrops(ModBlocks.BLACK_DOOR));
        addDrop(ModBlocks.BLACK_TRAPDOOR);
        addDrop(ModBlocks.BLACK_PRESSURE_PLATE);
        addDrop(ModBlocks.BLACK_BUTTON);
        addDrop(ModBlocks.BROWN_PLANKS);
        addDrop(ModBlocks.BROWN_STAIRS);
        addDrop(ModBlocks.BROWN_SLAB, slabDrops(ModBlocks.BROWN_SLAB));
        addDrop(ModBlocks.BROWN_FENCE);
        addDrop(ModBlocks.BROWN_FENCE_GATE);
        addDrop(ModBlocks.BROWN_DOOR, doorDrops(ModBlocks.BROWN_DOOR));
        addDrop(ModBlocks.BROWN_TRAPDOOR);
        addDrop(ModBlocks.BROWN_PRESSURE_PLATE);
        addDrop(ModBlocks.BROWN_BUTTON);
        addDrop(ModBlocks.RED_PLANKS);
        addDrop(ModBlocks.RED_STAIRS);
        addDrop(ModBlocks.RED_SLAB, slabDrops(ModBlocks.RED_SLAB));
        addDrop(ModBlocks.RED_FENCE);
        addDrop(ModBlocks.RED_FENCE_GATE);
        addDrop(ModBlocks.RED_DOOR, doorDrops(ModBlocks.RED_DOOR));
        addDrop(ModBlocks.RED_TRAPDOOR);
        addDrop(ModBlocks.RED_PRESSURE_PLATE);
        addDrop(ModBlocks.RED_BUTTON);
        addDrop(ModBlocks.ORANGE_PLANKS);
        addDrop(ModBlocks.ORANGE_STAIRS);
        addDrop(ModBlocks.ORANGE_SLAB, slabDrops(ModBlocks.ORANGE_SLAB));
        addDrop(ModBlocks.ORANGE_FENCE);
        addDrop(ModBlocks.ORANGE_FENCE_GATE);
        addDrop(ModBlocks.ORANGE_DOOR, doorDrops(ModBlocks.ORANGE_DOOR));
        addDrop(ModBlocks.ORANGE_TRAPDOOR);
        addDrop(ModBlocks.ORANGE_PRESSURE_PLATE);
        addDrop(ModBlocks.ORANGE_BUTTON);
        addDrop(ModBlocks.YELLOW_PLANKS);
        addDrop(ModBlocks.YELLOW_STAIRS);
        addDrop(ModBlocks.YELLOW_SLAB, slabDrops(ModBlocks.YELLOW_SLAB));
        addDrop(ModBlocks.YELLOW_FENCE);
        addDrop(ModBlocks.YELLOW_FENCE_GATE);
        addDrop(ModBlocks.YELLOW_DOOR, doorDrops(ModBlocks.YELLOW_DOOR));
        addDrop(ModBlocks.YELLOW_TRAPDOOR);
        addDrop(ModBlocks.YELLOW_PRESSURE_PLATE);
        addDrop(ModBlocks.YELLOW_BUTTON);
        addDrop(ModBlocks.LIME_PLANKS);
        addDrop(ModBlocks.LIME_STAIRS);
        addDrop(ModBlocks.LIME_SLAB, slabDrops(ModBlocks.LIME_SLAB));
        addDrop(ModBlocks.LIME_FENCE);
        addDrop(ModBlocks.LIME_FENCE_GATE);
        addDrop(ModBlocks.LIME_DOOR, doorDrops(ModBlocks.LIME_DOOR));
        addDrop(ModBlocks.LIME_TRAPDOOR);
        addDrop(ModBlocks.LIME_PRESSURE_PLATE);
        addDrop(ModBlocks.LIME_BUTTON);
        addDrop(ModBlocks.GREEN_PLANKS);
        addDrop(ModBlocks.GREEN_STAIRS);
        addDrop(ModBlocks.GREEN_SLAB, slabDrops(ModBlocks.GREEN_SLAB));
        addDrop(ModBlocks.GREEN_FENCE);
        addDrop(ModBlocks.GREEN_FENCE_GATE);
        addDrop(ModBlocks.GREEN_DOOR, doorDrops(ModBlocks.GREEN_DOOR));
        addDrop(ModBlocks.GREEN_TRAPDOOR);
        addDrop(ModBlocks.GREEN_PRESSURE_PLATE);
        addDrop(ModBlocks.GREEN_BUTTON);
        addDrop(ModBlocks.CYAN_PLANKS);
        addDrop(ModBlocks.CYAN_STAIRS);
        addDrop(ModBlocks.CYAN_SLAB, slabDrops(ModBlocks.CYAN_SLAB));
        addDrop(ModBlocks.CYAN_FENCE);
        addDrop(ModBlocks.CYAN_FENCE_GATE);
        addDrop(ModBlocks.CYAN_DOOR, doorDrops(ModBlocks.CYAN_DOOR));
        addDrop(ModBlocks.CYAN_TRAPDOOR);
        addDrop(ModBlocks.CYAN_PRESSURE_PLATE);
        addDrop(ModBlocks.CYAN_BUTTON);
        addDrop(ModBlocks.LIGHT_BLUE_PLANKS);
        addDrop(ModBlocks.LIGHT_BLUE_STAIRS);
        addDrop(ModBlocks.LIGHT_BLUE_SLAB, slabDrops(ModBlocks.LIGHT_BLUE_SLAB));
        addDrop(ModBlocks.LIGHT_BLUE_FENCE);
        addDrop(ModBlocks.LIGHT_BLUE_FENCE_GATE);
        addDrop(ModBlocks.LIGHT_BLUE_DOOR, doorDrops(ModBlocks.LIGHT_BLUE_DOOR));
        addDrop(ModBlocks.LIGHT_BLUE_TRAPDOOR);
        addDrop(ModBlocks.LIGHT_BLUE_PRESSURE_PLATE);
        addDrop(ModBlocks.LIGHT_BLUE_BUTTON);
        addDrop(ModBlocks.BLUE_PLANKS);
        addDrop(ModBlocks.BLUE_STAIRS);
        addDrop(ModBlocks.BLUE_SLAB, slabDrops(ModBlocks.BLUE_SLAB));
        addDrop(ModBlocks.BLUE_FENCE);
        addDrop(ModBlocks.BLUE_FENCE_GATE);
        addDrop(ModBlocks.BLUE_DOOR, doorDrops(ModBlocks.BLUE_DOOR));
        addDrop(ModBlocks.BLUE_TRAPDOOR);
        addDrop(ModBlocks.BLUE_PRESSURE_PLATE);
        addDrop(ModBlocks.BLUE_BUTTON);
        addDrop(ModBlocks.PURPLE_PLANKS);
        addDrop(ModBlocks.PURPLE_STAIRS);
        addDrop(ModBlocks.PURPLE_SLAB, slabDrops(ModBlocks.PURPLE_SLAB));
        addDrop(ModBlocks.PURPLE_FENCE);
        addDrop(ModBlocks.PURPLE_FENCE_GATE);
        addDrop(ModBlocks.PURPLE_DOOR, doorDrops(ModBlocks.PURPLE_DOOR));
        addDrop(ModBlocks.PURPLE_TRAPDOOR);
        addDrop(ModBlocks.PURPLE_PRESSURE_PLATE);
        addDrop(ModBlocks.PURPLE_BUTTON);
        addDrop(ModBlocks.MAGENTA_PLANKS);
        addDrop(ModBlocks.MAGENTA_STAIRS);
        addDrop(ModBlocks.MAGENTA_SLAB, slabDrops(ModBlocks.MAGENTA_SLAB));
        addDrop(ModBlocks.MAGENTA_FENCE);
        addDrop(ModBlocks.MAGENTA_FENCE_GATE);
        addDrop(ModBlocks.MAGENTA_DOOR, doorDrops(ModBlocks.MAGENTA_DOOR));
        addDrop(ModBlocks.MAGENTA_TRAPDOOR);
        addDrop(ModBlocks.MAGENTA_PRESSURE_PLATE);
        addDrop(ModBlocks.MAGENTA_BUTTON);
        addDrop(ModBlocks.PINK_PLANKS);
        addDrop(ModBlocks.PINK_STAIRS);
        addDrop(ModBlocks.PINK_SLAB, slabDrops(ModBlocks.PINK_SLAB));
        addDrop(ModBlocks.PINK_FENCE);
        addDrop(ModBlocks.PINK_FENCE_GATE);
        addDrop(ModBlocks.PINK_DOOR, doorDrops(ModBlocks.PINK_DOOR));
        addDrop(ModBlocks.PINK_TRAPDOOR);
        addDrop(ModBlocks.PINK_PRESSURE_PLATE);
        addDrop(ModBlocks.PINK_BUTTON);

        addDrop(ModBlocks.DARK_OAK_DOOR_WITH_WINDOWS, doorDrops(ModBlocks.DARK_OAK_DOOR_WITH_WINDOWS));
        addDrop(ModBlocks.DARK_OAK_TRAPDOOR_WITH_WINDOWS);
    }
}